In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load datasets

nav_df = pd.read_csv("../dataset/raw/02_nav_history.csv")

transactions_df = pd.read_csv("../dataset/raw/08_investor_transactions.csv")

performance_df = pd.read_csv("../dataset/raw/07_scheme_performance.csv")

In [3]:
print(nav_df.shape)
print(transactions_df.shape)
print(performance_df.shape)

(46000, 3)
(32778, 13)
(40, 19)

In [6]:
performance_df.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [5]:
transactions_df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [4]:
nav_df.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [7]:
# Dataset information
nav_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [8]:
# Check missing values
nav_df.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [9]:
# Convert date column to datetime
nav_df["date"] = pd.to_datetime(nav_df["date"])

In [10]:
# Sort by AMFI code and Date
nav_df = (
    nav_df
    .sort_values(["amfi_code", "date"])
    .reset_index(drop=True)
)

In [11]:
# Forward fill missing NAV
nav_df["nav"] = (
    nav_df
    .groupby("amfi_code")["nav"]
    .ffill()
)

In [12]:
before = len(nav_df)

nav_df = nav_df.drop_duplicates()

after = len(nav_df)

print(f"Duplicates Removed: {before-after}")

Duplicates Removed: 0

In [ ]:
invalid_nav = nav_df[nav_df["nav"] <= 0]

print(f"Invalid NAV Records: {len(invalid_nav)}")

invalid_nav.head()

In [13]:
nav_df.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [14]:
nav_df.to_csv(
    "../dataset/processed/nav_history_cleaned.csv",
    index=False
)

print("nav_history_cleaned.csv saved successfully.")

nav_history_cleaned.csv saved successfully.

In [15]:
transactions_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [16]:
transactions_df.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [17]:
transactions_df["transaction_date"] = pd.to_datetime(
    transactions_df["transaction_date"]
)

In [18]:
transactions_df["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [19]:
invalid_amount = transactions_df[
    transactions_df["amount_inr"] <= 0
]

print("Invalid Amount Records:", len(invalid_amount))

Invalid Amount Records: 0

In [21]:
transactions_df["kyc_status"].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [22]:
before = len(transactions_df)

transactions_df = transactions_df.drop_duplicates()

after = len(transactions_df)

print("Duplicates Removed:", before - after)

Duplicates Removed: 0

In [23]:
transactions_df.to_csv(
    "../dataset/processed/investor_transactions_cleaned.csv",
    index=False
)

print("investor_transactions_cleaned.csv saved successfully.")

investor_transactions_cleaned.csv saved successfully.

In [24]:
performance_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [25]:
performance_df.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [ ]:
return_cols = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct"
]

for col in return_cols:
    performance_df[col] = pd.to_numeric(
        performance_df[col],
        errors="coerce"
    )

In [26]:
return_cols = [
    "return_1yr_pct",
    "return_3yr_pct",
    "return_5yr_pct"
]

for col in return_cols:
    performance_df[col] = pd.to_numeric(
        performance_df[col],
        errors="coerce"
    )

In [27]:
invalid_expense = performance_df[
    (performance_df["expense_ratio_pct"] < 0.1) |
    (performance_df["expense_ratio_pct"] > 2.5)
]

print("Invalid Expense Ratio Records:", len(invalid_expense))

invalid_expense

Invalid Expense Ratio Records: 0

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [28]:
performance_df[
    return_cols
].describe()

       return_1yr_pct  return_3yr_pct  return_5yr_pct
count       40.000000       40.000000       40.000000
mean        14.376000       14.089000       14.516750
std          4.883023        4.617253        4.454021
min          4.260000        5.140000        5.430000
25%         11.735000       12.035000       12.340000
50%         14.620000       14.205000       14.185000
75%         16.392500       15.882500       17.585000
max         24.930000       23.390000       23.800000

In [29]:
before = len(performance_df)

performance_df = performance_df.drop_duplicates()

after = len(performance_df)

print("Duplicates Removed:", before - after)

Duplicates Removed: 0

In [30]:
performance_df.to_csv(
    "../dataset/processed/scheme_performance_cleaned.csv",
    index=False
)

print("scheme_performance_cleaned.csv saved successfully.")

scheme_performance_cleaned.csv saved successfully.